server:
  port: 9993
  servlet:
    context-path: /
eureka:
  instance:
    hostname: eureka-peer3
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka2019@eureka-peer1:9991/eureka/,http://eureka:eureka2019@eureka-peer2:9992/eureka/
    fetch-registry: false
    register-with-eureka: false
